# Script for Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines

pool:
  vmImage: $(vmImage)

steps:
- script: |
    echo my vmImage is $(vmImage)

- task: UseDotNet@2
  inputs:
    packageType: 'sdk' # Options: runtime, sdk
    version: '9.0.305'
    includePreviewVersions: true

- script: dotnet --version

- task: NugetToolInstaller@1
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: |
      **/pine.csproj
      **/Pine.IntegrationTests.csproj

- script: dotnet  run  --project ./prebuild/prebuild.csproj  --configuration Release
  displayName: 'Prebuild'
  workingDirectory: ./implement/

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: test
    projects: |
      **/Pine.IntegrationTests.csproj
    arguments:  --logger trx
    publishTestResults: false

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish ./implement/pine/pine.csproj
  displayName: 'publish web host'
